"""
Tag Taxonomy and Normalization.
This module handles the project's controlled vocabulary, ensuring that tags
generated by LLMs are normalized and matched against an optional user-defined
taxonomy file (taxonomy.yml).
"""
import re
import unicodedata
from pathlib import Path
from typing import Optional

import yaml

from grimoire.utils.logger import get_logger

logger = get_logger(__name__)


class Taxonomy:
    """
    Handles tag normalization and reconciliation against a controlled vocabulary.
    """
    def __init__(self, controlled_vocabulary: Optional[list[str]] = None):
        self.vocabulary: list[str] = list(controlled_vocabulary or [])
        # Pre-calculate a mapping from normalized form to canonical form
        self.norm_map: dict[str, str] = {
            self.normalize(tag): tag for tag in self.vocabulary
        }

    def normalize(self, tag: str) -> str:
        """
        Normalizes a tag: lowercase, no accents, non-alnum characters replaced by hyphens.
        Example: "Ocultismo Clásico" → "ocultismo-clasico"
        """
        tag = tag.lower().strip()
        # Remove accents/diacritics
        tag = "".join(
            c for c in unicodedata.normalize("NFD", tag)
            if unicodedata.category(c) != "Mn"
        )
        # Replace non-alphanumeric with hyphens
        tag = re.sub(r"[^a-z0-9]+", "-", tag)
        return tag.strip("-")

    def reconcile(self, tags: list[str]) -> list[str]:
        """
        Dedupes tags and maps them to their canonical vocabulary spelling if available.
        Expects tags to be already normalized.
        """
        seen: set[str] = set()
        out: list[str] = []
        for tag in tags:
            if not tag:
                continue
            # Use canonical spelling from vocabulary if it exists, otherwise use the tag as is
            canonical = self.norm_map.get(tag, tag)
            if canonical in seen:
                continue
            seen.add(canonical)
            out.append(canonical)
        return out


def load_taxonomy_from_vault(vault_path: Path) -> Taxonomy:
    """
    Loads the controlled vocabulary from a 'taxonomy.yml' file in the vault root.
    
    Expected format:
    vocabulary:
      - tag1
      - tag2
    """
    candidate = Path(vault_path) / "taxonomy.yml"
    if not candidate.exists():
        return Taxonomy()

    try:
        raw = candidate.read_text(encoding="utf-8")
        data = yaml.safe_load(raw) or {}
    except (OSError, yaml.YAMLError) as e:
        logger.warning("taxonomy_load_failed", path=str(candidate), error=str(e))
        return Taxonomy()

    vocab = data.get("vocabulary") if isinstance(data, dict) else None
    if not isinstance(vocab, list):
        logger.warning("taxonomy_no_vocabulary", path=str(candidate))
        return Taxonomy()

    # Filter and clean vocabulary items
    vocabulary = [str(x).strip() for x in vocab if isinstance(x, (str, int))]
    vocabulary = [v for v in vocabulary if v]
    logger.info("taxonomy_loaded", path=str(candidate), size=len(vocabulary))
    return Taxonomy(vocabulary)
